/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * AMS API
 * AMS API documentation
 * OpenAPI spec version: 1.0
 */
import type { CreateSurveyDtoType } from './createSurveyDtoType';

export interface CreateSurveyDto {
  name: string;
  description?: string;
  type: CreateSurveyDtoType;
  startDate: string;
  endDate: string;
}
