/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * AMS API
 * AMS API documentation
 * OpenAPI spec version: 1.0
 */

export type CreateSurveyDtoType =
  (typeof CreateSurveyDtoType)[keyof typeof CreateSurveyDtoType];

export const CreateSurveyDtoType = {
  COURSE_INVENTORY: 'COURSE_INVENTORY',
} as const;
