/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * AMS API
 * AMS API documentation
 * OpenAPI spec version: 1.0
 */
import type { GetCourseDto } from './getCourseDto';
import type { GetPromotionRequirementDtoType } from './getPromotionRequirementDtoType';
import type { GetRankDto } from './getRankDto';

export interface GetPromotionRequirementDto {
  id: string;
  type: GetPromotionRequirementDtoType;
  /** @nullable */
  minYears?: number | null;
  /** @nullable */
  requiredRank?: GetRankDto | null;
  /** @nullable */
  requiredCourse?: GetCourseDto | null;
  /** @nullable */
  groupKey?: string | null;
}
