/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AMS API
 * AMS API documentation
 * OpenAPI spec version: 1.0
 */

export type GetPromotionRequirementDtoType =
  (typeof GetPromotionRequirementDtoType)[keyof typeof GetPromotionRequirementDtoType];

export const GetPromotionRequirementDtoType = {
  MIN_YEARS_IN_RANK: 'MIN_YEARS_IN_RANK',
  MIN_YEARS_TOTAL_SERVICE: 'MIN_YEARS_TOTAL_SERVICE',
  REQUIRED_COURSE: 'REQUIRED_COURSE',
  REQUIRED_RANK: 'REQUIRED_RANK',
} as const;
