/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AMS API
 * AMS API documentation
 * OpenAPI spec version: 1.0
 */
import type { GetPromotionRequirementDto } from './getPromotionRequirementDto';
import type { GetPromotionRequirementGroupDtoGroupKey } from './getPromotionRequirementGroupDtoGroupKey';

export interface GetPromotionRequirementGroupDto {
  /** @nullable */
  groupKey: GetPromotionRequirementGroupDtoGroupKey;
  requirements: GetPromotionRequirementDto[];
}
