/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * AMS API
 * AMS API documentation
 * OpenAPI spec version: 1.0
 */

export interface GetSurveyDto {
  id: string;
  name: string;
  description: string;
  type: string;
  startDate: string;
  endDate: string;
  createdAt: string;
}
