/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * AMS API
 * AMS API documentation
 * OpenAPI spec version: 1.0
 */

export interface GetUserDto {
  id: string;
  mpid: string;
  keycloakId: string;
  name: string;
  email: string;
  joinedAt: string;
  createdAt: string;
  updatedAt: string;
  addressId: string;
  rankId: string;
}
