/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * AMS API
 * AMS API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type HealthControllerDetails200Info = {
  [key: string]: {
    status: string;
    [key: string]: unknown;
  };
} | null;
