/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * AMS API
 * AMS API documentation
 * OpenAPI spec version: 1.0
 */
import type { CreateAddressDto } from './createAddressDto';

export interface UpdateLocationDto {
  name?: string;
  address?: CreateAddressDto;
}
