/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * AMS API
 * AMS API documentation
 * OpenAPI spec version: 1.0
 */

export type UpdateSurveyDtoType =
  (typeof UpdateSurveyDtoType)[keyof typeof UpdateSurveyDtoType];

export const UpdateSurveyDtoType = {
  COURSE_INVENTORY: 'COURSE_INVENTORY',
} as const;
