/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * AMS API
 * AMS API documentation
 * OpenAPI spec version: 1.0
 */
import type { UpdateSurveyDtoType } from './updateSurveyDtoType';

export interface UpdateSurveyDto {
  name?: string;
  description?: string;
  type?: UpdateSurveyDtoType;
  startDate?: string;
  endDate?: string;
}
