/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * AMS API
 * AMS API documentation
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { CreateSurveyDto, GetSurveyDto } from '../model';

export type surveyControllerCreateSurveyResponse201 = {
  data: GetSurveyDto;
  status: 201;
};

export type surveyControllerCreateSurveyResponseSuccess =
  surveyControllerCreateSurveyResponse201 & {
    headers: Headers;
  };
export type surveyControllerCreateSurveyResponse =
  surveyControllerCreateSurveyResponseSuccess;

export const getSurveyControllerCreateSurveyUrl = () => {
  return `/api/v1/surveys`;
};

export const surveyControllerCreateSurvey = async (
  createSurveyDto: CreateSurveyDto,
  options?: RequestInit
): Promise<surveyControllerCreateSurveyResponse> => {
  const res = await fetch(getSurveyControllerCreateSurveyUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createSurveyDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: surveyControllerCreateSurveyResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as surveyControllerCreateSurveyResponse;
};

export const getSurveyControllerCreateSurveyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof surveyControllerCreateSurvey>>,
    TError,
    { data: CreateSurveyDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof surveyControllerCreateSurvey>>,
  TError,
  { data: CreateSurveyDto },
  TContext
> => {
  const mutationKey = ['surveyControllerCreateSurvey'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof surveyControllerCreateSurvey>>,
    { data: CreateSurveyDto }
  > = (props) => {
    const { data } = props ?? {};

    return surveyControllerCreateSurvey(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SurveyControllerCreateSurveyMutationResult = NonNullable<
  Awaited<ReturnType<typeof surveyControllerCreateSurvey>>
>;
export type SurveyControllerCreateSurveyMutationBody = CreateSurveyDto;
export type SurveyControllerCreateSurveyMutationError = unknown;

export const useSurveyControllerCreateSurvey = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof surveyControllerCreateSurvey>>,
      TError,
      { data: CreateSurveyDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof surveyControllerCreateSurvey>>,
  TError,
  { data: CreateSurveyDto },
  TContext
> => {
  return useMutation(
    getSurveyControllerCreateSurveyMutationOptions(options),
    queryClient
  );
};
export type surveyControllerGetAllSurveysResponse200 = {
  data: GetSurveyDto[];
  status: 200;
};

export type surveyControllerGetAllSurveysResponseSuccess =
  surveyControllerGetAllSurveysResponse200 & {
    headers: Headers;
  };
export type surveyControllerGetAllSurveysResponse =
  surveyControllerGetAllSurveysResponseSuccess;

export const getSurveyControllerGetAllSurveysUrl = () => {
  return `/api/v1/surveys`;
};

export const surveyControllerGetAllSurveys = async (
  options?: RequestInit
): Promise<surveyControllerGetAllSurveysResponse> => {
  const res = await fetch(getSurveyControllerGetAllSurveysUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: surveyControllerGetAllSurveysResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as surveyControllerGetAllSurveysResponse;
};

export const getSurveyControllerGetAllSurveysQueryKey = () => {
  return [`/api/v1/surveys`] as const;
};

export const getSurveyControllerGetAllSurveysQueryOptions = <
  TData = Awaited<ReturnType<typeof surveyControllerGetAllSurveys>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof surveyControllerGetAllSurveys>>,
      TError,
      TData
    >
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSurveyControllerGetAllSurveysQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof surveyControllerGetAllSurveys>>
  > = ({ signal }) =>
    surveyControllerGetAllSurveys({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof surveyControllerGetAllSurveys>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SurveyControllerGetAllSurveysQueryResult = NonNullable<
  Awaited<ReturnType<typeof surveyControllerGetAllSurveys>>
>;
export type SurveyControllerGetAllSurveysQueryError = unknown;

export function useSurveyControllerGetAllSurveys<
  TData = Awaited<ReturnType<typeof surveyControllerGetAllSurveys>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof surveyControllerGetAllSurveys>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof surveyControllerGetAllSurveys>>,
          TError,
          Awaited<ReturnType<typeof surveyControllerGetAllSurveys>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSurveyControllerGetAllSurveys<
  TData = Awaited<ReturnType<typeof surveyControllerGetAllSurveys>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof surveyControllerGetAllSurveys>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof surveyControllerGetAllSurveys>>,
          TError,
          Awaited<ReturnType<typeof surveyControllerGetAllSurveys>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSurveyControllerGetAllSurveys<
  TData = Awaited<ReturnType<typeof surveyControllerGetAllSurveys>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof surveyControllerGetAllSurveys>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useSurveyControllerGetAllSurveys<
  TData = Awaited<ReturnType<typeof surveyControllerGetAllSurveys>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof surveyControllerGetAllSurveys>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSurveyControllerGetAllSurveysQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type surveyControllerGetSurveyByIdResponse200 = {
  data: GetSurveyDto;
  status: 200;
};

export type surveyControllerGetSurveyByIdResponseSuccess =
  surveyControllerGetSurveyByIdResponse200 & {
    headers: Headers;
  };
export type surveyControllerGetSurveyByIdResponse =
  surveyControllerGetSurveyByIdResponseSuccess;

export const getSurveyControllerGetSurveyByIdUrl = (id: string) => {
  return `/api/v1/surveys/${id}`;
};

export const surveyControllerGetSurveyById = async (
  id: string,
  options?: RequestInit
): Promise<surveyControllerGetSurveyByIdResponse> => {
  const res = await fetch(getSurveyControllerGetSurveyByIdUrl(id), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: surveyControllerGetSurveyByIdResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as surveyControllerGetSurveyByIdResponse;
};

export const getSurveyControllerGetSurveyByIdQueryKey = (id: string) => {
  return [`/api/v1/surveys/${id}`] as const;
};

export const getSurveyControllerGetSurveyByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof surveyControllerGetSurveyById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof surveyControllerGetSurveyById>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  }
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSurveyControllerGetSurveyByIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof surveyControllerGetSurveyById>>
  > = ({ signal }) =>
    surveyControllerGetSurveyById(id, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof surveyControllerGetSurveyById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SurveyControllerGetSurveyByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof surveyControllerGetSurveyById>>
>;
export type SurveyControllerGetSurveyByIdQueryError = unknown;

export function useSurveyControllerGetSurveyById<
  TData = Awaited<ReturnType<typeof surveyControllerGetSurveyById>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof surveyControllerGetSurveyById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof surveyControllerGetSurveyById>>,
          TError,
          Awaited<ReturnType<typeof surveyControllerGetSurveyById>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSurveyControllerGetSurveyById<
  TData = Awaited<ReturnType<typeof surveyControllerGetSurveyById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof surveyControllerGetSurveyById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof surveyControllerGetSurveyById>>,
          TError,
          Awaited<ReturnType<typeof surveyControllerGetSurveyById>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSurveyControllerGetSurveyById<
  TData = Awaited<ReturnType<typeof surveyControllerGetSurveyById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof surveyControllerGetSurveyById>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useSurveyControllerGetSurveyById<
  TData = Awaited<ReturnType<typeof surveyControllerGetSurveyById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof surveyControllerGetSurveyById>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSurveyControllerGetSurveyByIdQueryOptions(
    id,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
