/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AMS API
 * AMS API documentation
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { GetPromotionRequirementsByRankDto } from '.././model';

export type promotionRequirementControllerGetAllResponse200 = {
  data: GetPromotionRequirementsByRankDto[];
  status: 200;
};

export type promotionRequirementControllerGetAllResponseSuccess =
  promotionRequirementControllerGetAllResponse200 & {
    headers: Headers;
  };
export type promotionRequirementControllerGetAllResponse =
  promotionRequirementControllerGetAllResponseSuccess;

export const getPromotionRequirementControllerGetAllUrl = () => {
  return `/api/v1/promotion-requirements`;
};

export const promotionRequirementControllerGetAll = async (
  options?: RequestInit
): Promise<promotionRequirementControllerGetAllResponse> => {
  const res = await fetch(getPromotionRequirementControllerGetAllUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: promotionRequirementControllerGetAllResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as promotionRequirementControllerGetAllResponse;
};

export const getPromotionRequirementControllerGetAllQueryKey = () => {
  return [`/api/v1/promotion-requirements`] as const;
};

export const getPromotionRequirementControllerGetAllQueryOptions = <
  TData = Awaited<ReturnType<typeof promotionRequirementControllerGetAll>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof promotionRequirementControllerGetAll>>,
      TError,
      TData
    >
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPromotionRequirementControllerGetAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof promotionRequirementControllerGetAll>>
  > = ({ signal }) =>
    promotionRequirementControllerGetAll({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof promotionRequirementControllerGetAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PromotionRequirementControllerGetAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof promotionRequirementControllerGetAll>>
>;
export type PromotionRequirementControllerGetAllQueryError = unknown;

export function usePromotionRequirementControllerGetAll<
  TData = Awaited<ReturnType<typeof promotionRequirementControllerGetAll>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof promotionRequirementControllerGetAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof promotionRequirementControllerGetAll>>,
          TError,
          Awaited<ReturnType<typeof promotionRequirementControllerGetAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePromotionRequirementControllerGetAll<
  TData = Awaited<ReturnType<typeof promotionRequirementControllerGetAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof promotionRequirementControllerGetAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof promotionRequirementControllerGetAll>>,
          TError,
          Awaited<ReturnType<typeof promotionRequirementControllerGetAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePromotionRequirementControllerGetAll<
  TData = Awaited<ReturnType<typeof promotionRequirementControllerGetAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof promotionRequirementControllerGetAll>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function usePromotionRequirementControllerGetAll<
  TData = Awaited<ReturnType<typeof promotionRequirementControllerGetAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof promotionRequirementControllerGetAll>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getPromotionRequirementControllerGetAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
